name: Build macOS Version

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install System Dependencies
      run: |
        brew install portaudio

    - name: Install Python Dependencies
      run: |
        export CFLAGS="-I$(brew --prefix)/include"
        export LDFLAGS="-L$(brew --prefix)/lib"
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller VoxTranslatePro.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VoxTranslatePro-macOS
        path: dist/VoxTranslatePro.app
